spring.application.name=PROYECTOFINALTESTS
server.port=8080

spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:h2:file:~/data/mundial2026;
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Configuracion del correo
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mundial2026desarrollo3@gmail.com
spring.mail.password=virvvktiesiphcfu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
